language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
- yarn build-storybook
deploy:
  provider: firebase
  token:
    secure: Y8lWJSCsxns8DfGDFvX5Q7oHJhkL6OyRNJtcL03ggoUGd4cKbtALcWgX33mubn1Qc5cd4O5oepi4NrnA4qDHWGxxkeX38bAXFxh222xqVgyXkUljn3QnCqCSRWvnpiTSzhLxS3XD7kwnlEjGh4MEGDx7HZyje1ZP59bHs9ZJ6s3ALICMljpCHL3z+eDT2JbSh3MfZ/axSP0T08nkoq9dctkBeG8QHNG/MS6rvKan7DVcWJvhDNfb4TtsZwb/sxhyZ+dts8WOnL2Onf8ZTa6+8Fxt2OhV4Dc1h9gD6Yb5Pczz/N6pYjGsAJTegnGsYiRae+vm9rAFThYybS58vzPrE5EWqgnH0auoOOR+a4H0DHzueSFtg7Ve7F9gC7xgjzn4mtb+en+ENHKC4OibnNUHX9QyjWoQpBZQSqp/Cpk2hNY9BxtHGvbknxjuGo/pMxzY/LdnZ5/QZAkPz4HlPQ9RbA2ovM1zvOrw4WFO63VB0Rs6WQ0viRXFUzKSCKwHCOzWTZRAL8ldciJ9VdYyHZZ0/nlnmqI0+OXA3LtHXUerAg6r9f0MLZ1ho2d3MSItNda+eZ3MTfuwSgDKPf7ZW5ZJEUBDGRVjb1DiKcDYINr4jom4pxDyASJt95D2y9GWY8M755CpTLjEaqUDTywiOwFnfOMFOo92201d5hBbB0SBSvI=
after_success:
- npm run report-coverage
notifications:
  slack:
    on_success: change
    on_failure: change
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
