sudo: true
language: node_js
node_js:
  - '10'
cache:
  directories:
    - node_modules
script:
  - yarn test
deploy:
  provider: firebase
  skip_cleanup: true
after_success:
  - npm run report-coverage
notifications:
  slack:
    on_success: change
    on_failure: change
before_install:
  - yarn global add greenkeeper-lockfile@1
  - export PATH=$PATH:`yarn global bin`
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
jobs:
  include:
    - stage: build docker image
      script:
        - echo $DOCKER_USERNAME $TEST
        - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
        - docker build -t ratatouille .
        - docker images
        - docker tag ratatouille $DOCKER_USERNAME/ratatouille
        - docker push $DOCKER_USERNAME/ratatouille
