language: node_js
node_js:
  - "10"
directories:
  - node_modules
script:
  - yarn test
  - yarn build
before_deploy:
  - git tag "$(date +'%Y%m%d-%H%M%S')-$(git log --format=%h -1)"
  - tar --directory=build -zcf bundle.tar.gz .
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: bundle.tar.gz
    on:
      repo: Artsdatabanken/nin-innsyn
    skip_cleanup: true
  - provider: script
    script: deploy.sh
    on:
      branch: evensen
    skip_cleanup: true
after_deploy: ./slack.sh ops "deploy nin-innsyn"
after_success:
  - npm run report-coverage
notifications:
  slack:
    on_success: change
    on_failure: change
before_install:
  - yarn global add greenkeeper-lockfile@1
  - export PATH=$PATH:`yarn global bin`
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
