sudo: true
language: node_js
node_js:
  - '10'
services:
  - docker
directories:
  - node_modules
script:
  - yarn test
deploy:
  skip_cleanup: true
  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t ratatouille .
    - docker images
    - docker push Artsdatabanken/ratatouille:latest
after_success:
  - npm run report-coverage
notifications:
  slack:
    on_success: change
    on_failure: change
before_install:
  - yarn global add greenkeeper-lockfile@1
  - export PATH=$PATH:`yarn global bin`
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
