language: node_js
node_js:
- '10'
directories:
- node_modules
script:
- yarn test
deploy:
  provider: releases
  api_key:
    secure: fgepmhVu6OzpSvzsjwd+k4su9TCcroQ/fHpTgOLNkUKPhg6n9K3aegZJgusoBTOCBLffutBg2qSGvO/nKstDpMqKYU2O7q9QB46tlaclrEPT4p3QIG/xfFXshSCQOugex/kzqagWj+2yGxWJJ3HA8ttio3lcW/wUxC8GIUmF764Asgh5xWo/Ftk+Ui/FtYkDciM8+7riiGynI2CGOS5GodQKx360c6jKW2vqzkaRCGqeu5POT/VlGM7uwmpWxDwpinxfeqUnESVRc89coHlVv9yKFC7YDYHa+xDoMgORbpUaeqUs+2WF4gaKwjXqVF8b6Sc6b33/4C+hwmFAW8INMYA+lJXpAnBweS5xsH5s1WzO8s2zwpPgRgvSRrkvv7qN6IIqpFHCJOExN2lbhJfdJMdzgll60UeJsS6LqqoYxlJTxOFAXh8Olp3dYaBu5/Ru9es5cTrWDm8E6qCfcwQ/k/sFh/7v7Thr/ROdCZ5BIqyDFVGsH6tr4/aGogXsNitYQnFrO618JkXO759X6QCrw9431d136O+ft1luVkXJjOjGbKWgBKPur7XLSlpBUPJoPtSqwXsZ9BrAaEi07L1kkTW+nJPsRoZtwFsGW+lkqxoZyQ8daaKWw1euF/2JSunuJgL00mXQL4D/UNfbt1NUyjec+6iJoyZMjDyahPLYNV0=
  file: build/*
  on:
    repo: Artsdatabanken/ratatouille
after_deploy:
  notifications:
    slack:
      template:
      - release %{repository_slug}
after_success:
- npm run report-coverage
notifications:
  slack:
    secure: boRuTnFbZmvMYN4U4cqEhd3TAetZrHC2uUNmrLu/oEgKMWRtBQMJATiV/dYuYki1zWz1OeF97dAwAZnJpDCH7S4Sv+Dskn75HUj0NAVKfxR/mH/MiQupNLe4eN3+5FfhzdQW+n8m/rLcnPT5RuAd4+xjUeGc4aAPuYPpi8IMKoIV6aXRSNBpZMGpjQuyV6DZMhUr5Rr/WUD0DwxJSzbXZsNFUdefVBrogeLl9GKcxWapSNSED3tzZyG7MexfiD3cdw6GWpwuAmNjKyTe2BA8aESUvuBcOPSk/z7ZqAxC0GOW8BEikEMowAK+nVUOYL4bbyTBvpa1808Fu9EWBxreBNH9nwG91s+zXLmNFt+cLMp6rozedPG6JuOCT4tDHdqRrrCubNmpNVczn1iY6iyPj1q7Cvk+s+kfugrdedmqr/aYhatnirGGxdAbHAluizkwAzbzP6gnD4i2FdxefJ77hrAI80Y/6wMzPHTWVCgVUZEyBZb6J+1C7JvcEinsnNC0MkOdvGBcCNUHEGc+L/clYhVN5W4CoqP5QxuatZjYhfPlIe4D4v51wgttu4IQN7FztZwvSzSVMKdONtbhFv3jOuyKsm/KQONEBs+7o9exNm5pPR1GLJfpjNO9vJJJ9K3b8ene+L0Irnv0SWu/mpl0+shbAkfrrQX9MJUT3ntXuaM=
before_install:
- yarn global add greenkeeper-lockfile@1
- export PATH=$PATH:`yarn global bin`
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
