language: node_js
node_js:
- '10'
directories:
- node_modules
script:
- yarn test
- yarn build
before_deploy:
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- echo "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- ls -la build
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: build/*
  on:
    repo: Artsdatabanken/ratatouille
  skip_cleanup: true
#  api-key:
#    secure: CyJ1W9ZSYTdfkOJoQSGPhDG83V2Y2ekZR3b05a95meh8CSNER3y79NdqnkUxNXrkPgHlFRbDYbdyiiEuSCqyF8LzFcdDKbOfpYzkBu2XJbmSUDtxCcjiyWBjfqx1M7QTdSmOrw6URRjtCpeH3PaVx7dPeceWlQTSIqzf6gXRK+1REsJzT759HLzG7gjbpty23U9uOSKWLxcBRqgLjQZTs5EN0MpREjVkO5xsv+IM2NhXYIYpMj8ygYy6QUt8HztNjGF31e8k5dyVWtskZ0gXdxgkKxVwDqL26BgYZVxbbdNfxjXJOuIJQAnecObwy0LVzzutb+Gw5BZftq+r9T/xbddx+U0rZ5HtCrXT5UsCJeEh97dxAWFVQ7hGnkyeEXfO/MlwlBd3bu2J55AzSTrVcGJKMsJZH+/z+xmKgF48FQ9i5aaxgjfPP7RoRTwNOFEQfAKuTG8HdYweSNo5zFDnWWS3I/mfHZeVEvEDv2BjDJJAoVA4M0l713rjZFPA6+rF+gKBKNs8u1iq+TveHFSCXFWeS9QW4e0KdICvs6ruPX1OLJ79STL9wUqHI8pgQ8KGlKZHLpBEUxhsJez7VyVp7BlGwyapXUrK8xGp7sbdnR9xMm6kHb7g+HEjcEXhh1EPHmGZ4YCCmg9WXnUddvRJ2kltqoiHtQHMEkJrG7NzaN0=
after_deploy:
  notifications:
    slack:
      template:
      - release %{repository_slug}
after_success:
- npm run report-coverage
notifications:
  slack:
    secure: boRuTnFbZmvMYN4U4cqEhd3TAetZrHC2uUNmrLu/oEgKMWRtBQMJATiV/dYuYki1zWz1OeF97dAwAZnJpDCH7S4Sv+Dskn75HUj0NAVKfxR/mH/MiQupNLe4eN3+5FfhzdQW+n8m/rLcnPT5RuAd4+xjUeGc4aAPuYPpi8IMKoIV6aXRSNBpZMGpjQuyV6DZMhUr5Rr/WUD0DwxJSzbXZsNFUdefVBrogeLl9GKcxWapSNSED3tzZyG7MexfiD3cdw6GWpwuAmNjKyTe2BA8aESUvuBcOPSk/z7ZqAxC0GOW8BEikEMowAK+nVUOYL4bbyTBvpa1808Fu9EWBxreBNH9nwG91s+zXLmNFt+cLMp6rozedPG6JuOCT4tDHdqRrrCubNmpNVczn1iY6iyPj1q7Cvk+s+kfugrdedmqr/aYhatnirGGxdAbHAluizkwAzbzP6gnD4i2FdxefJ77hrAI80Y/6wMzPHTWVCgVUZEyBZb6J+1C7JvcEinsnNC0MkOdvGBcCNUHEGc+L/clYhVN5W4CoqP5QxuatZjYhfPlIe4D4v51wgttu4IQN7FztZwvSzSVMKdONtbhFv3jOuyKsm/KQONEBs+7o9exNm5pPR1GLJfpjNO9vJJJ9K3b8ene+L0Irnv0SWu/mpl0+shbAkfrrQX9MJUT3ntXuaM=
before_install:
- yarn global add greenkeeper-lockfile@1
- export PATH=$PATH:`yarn global bin`
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
